export const metadata = {
  title: 'Next Pizza | Dashboard',
  description: 'Generated by Next.js',
};

export default function DashboardLayout({ children }: { children: React.ReactNode }) {
  return (
    <>
      <header>DASHBOARD HEADER</header>
      {children}
    </>
  );
}

